import samsung changes

diff --git a/scripts/Makefile.lib b/scripts/Makefile.lib
--- a/scripts/Makefile.lib
+++ b/scripts/Makefile.lib
@@ -261,6 +261,12 @@ dtc_cpp_flags  = -Wp,-MMD,$(depfile).pre.tmp -nostdinc                    \
 		 $(addprefix -I,$(DTC_INCLUDE))                          \
 		 -undef -D__DTS__
 
+ifeq ($(CONFIG_SEC_FACTORY),y)
+dtc_cpp_flags += -DCONFIG_SEC_FACTORY
+ifeq ($(CONFIG_SEC_FACTORY_INTERPOSER),y)
+dtc_cpp_flags += -DCONFIG_SEC_FACTORY_INTERPOSER
+endif
+endif
 ifdef CONFIG_OBJTOOL
 
 objtool := $(objtree)/tools/objtool/objtool
@@ -398,6 +404,20 @@ quiet_cmd_wrap_S_dtb = WRAP    $@
 $(obj)/%.dtb.S: $(obj)/%.dtb FORCE
 	$(call if_changed,wrap_S_dtb)
 
+show_dtc_error =                                                          \
+(                                                                         \
+	cat $1 >&2;                                                       \
+	for err in "$$(cat $1 | grep 'Error:')"; do                       \
+	   echo "See more detail error as below:" >&2;                    \
+	   cat $$(echo $$err | cut -d':' -f2)                             \
+	   | awk '{printf("ERROR: %6d  %s\n"), NR, $$0}'                  \
+	   | head -n $$(echo $$err | grep -Eo ':[0-9]+' | cut -d':' -f2)  \
+	   | tail -n 2 >&2;                                               \
+	done;                                                             \
+	rm $1;                                                            \
+	false;                                                            \
+)
+
 $(obj)/%.dtbo.S: $(obj)/%.dtbo FORCE
 	$(call if_changed,wrap_S_dtb)
 
@@ -405,7 +425,8 @@ quiet_cmd_dtc = DTC     $@
 cmd_dtc = $(HOSTCC) -E $(dtc_cpp_flags) -x assembler-with-cpp -o $(dtc-tmp) $< ; \
 	$(DTC) -o $@ -b 0 \
 		$(addprefix -i,$(dir $<) $(DTC_INCLUDE)) $(DTC_FLAGS) \
-		-d $(depfile).dtc.tmp $(dtc-tmp) ; \
+			-d $(depfile).dtc.tmp $(dtc-tmp) 2>$@.dtout || $(call show_dtc_error, $@.dtout) ;\
+	$(DTC) -q -O dts -I dtb -o $@.reverse.dts $@ ; \
 	cat $(depfile).pre.tmp $(depfile).dtc.tmp > $(depfile)
 
 # NOTE:
